{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 0.インポート"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 評価に使う関数\n",
    "from scripts.evaluate import experiment"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 1. DeepDenoiserでの実験（Default）"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1-1. 簡易版"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import seisbench.models as sbm\n",
    "\n",
    "# model = sbm.DeepDenoiser.from_pretrained(\"original\")\n",
    "# experiment(model, \"DeepDenoiser\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1-2. 本体"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ①準備"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import argparse\n",
    "import sys\n",
    "from tensorflow.keras.models import load_model\n",
    "\n",
    "sys.path.append('../model/DeepDenoiser/deepdenoiser')\n",
    "\n",
    "from train import main\n",
    "from model import WrappedModel"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ②モデルの学習"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-04-17 16:28:58,977 Dataset size: training 100, validation 0\n",
      "2025-04-17 16:28:58,977 Training log: ./log/250417-162858\n",
      "2025-04-17 16:28:58,980 Model: depths 6, filters 8, filter size 3x3, pool size: 2x2, dilation rate: 1x1\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:201: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.\n",
      "  net = tf.compat.v1.layers.conv2d(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:214: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).\n",
      "  net = tf.compat.v1.layers.batch_normalization(net, training=self.is_training, name=\"input_bn\")\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:217: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.\n",
      "  net = tf.compat.v1.layers.dropout(net, rate=self.drop_rate, training=self.is_training, name=\"input_dropout\")\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:223: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.\n",
      "  net = tf.compat.v1.layers.conv2d(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:236: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).\n",
      "  net = tf.compat.v1.layers.batch_normalization(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:240: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.\n",
      "  net = tf.compat.v1.layers.dropout(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:247: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.\n",
      "  net = tf.compat.v1.layers.conv2d(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:261: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).\n",
      "  net = tf.compat.v1.layers.batch_normalization(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:265: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.\n",
      "  net = tf.compat.v1.layers.dropout(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:273: UserWarning: `tf.layers.conv2d_transpose` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2DTranspose` instead.\n",
      "  net = tf.compat.v1.layers.conv2d_transpose(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:286: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).\n",
      "  net = tf.compat.v1.layers.batch_normalization(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:290: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.\n",
      "  net = tf.compat.v1.layers.dropout(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:298: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.\n",
      "  net = tf.compat.v1.layers.conv2d(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:311: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).\n",
      "  net = tf.compat.v1.layers.batch_normalization(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:315: UserWarning: `tf.layers.dropout` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dropout` instead.\n",
      "  net = tf.compat.v1.layers.dropout(\n",
      "/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/model.py:321: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.\n",
      "  net = tf.compat.v1.layers.conv2d(\n",
      "2025-04-17 16:29:01.097799: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled\n",
      "2025-04-17 16:29:01,403 restoring models...\n",
      "250417-162858: epoch=0, loss=0.525034, mean loss=0.525034: 100%|██████████| 5/5 [00:02<00:00,  1.92it/s]\n",
      "250417-162858: epoch=1, loss=0.525175, mean loss=0.525062: 100%|██████████| 5/5 [00:00<00:00,  8.55it/s]\n",
      "250417-162858: epoch=2, loss=0.488662, mean loss=0.521463: 100%|██████████| 5/5 [00:00<00:00,  8.67it/s]\n",
      "250417-162858: epoch=3, loss=0.462129, mean loss=0.514866: 100%|██████████| 5/5 [00:00<00:00,  8.64it/s]\n",
      "250417-162858: epoch=4, loss=0.505485, mean loss=0.508254: 100%|██████████| 5/5 [00:00<00:00,  8.60it/s]\n",
      "250417-162858: epoch=5, loss=0.451965, mean loss=0.502841: 100%|██████████| 5/5 [00:00<00:00,  8.60it/s]\n",
      "250417-162858: epoch=6, loss=0.451251, mean loss=0.495594: 100%|██████████| 5/5 [00:00<00:00,  7.92it/s]\n",
      "250417-162858: epoch=7, loss=0.426999, mean loss=0.487368: 100%|██████████| 5/5 [00:00<00:00,  8.59it/s]\n",
      "250417-162858: epoch=8, loss=0.451921, mean loss=0.482669: 100%|██████████| 5/5 [00:00<00:00,  8.51it/s]\n",
      "250417-162858: epoch=9, loss=0.474605, mean loss=0.481527: 100%|██████████| 5/5 [00:00<00:00,  8.56it/s]\n",
      "250417-162858: epoch=10, loss=0.490893, mean loss=0.479531: 100%|██████████| 5/5 [00:00<00:00,  8.57it/s]\n",
      "250417-162858: epoch=11, loss=0.422320, mean loss=0.476166: 100%|██████████| 5/5 [00:00<00:00,  8.72it/s]\n",
      "250417-162858: epoch=12, loss=0.449125, mean loss=0.472358: 100%|██████████| 5/5 [00:00<00:00,  8.59it/s]\n",
      "250417-162858: epoch=13, loss=0.401159, mean loss=0.470293: 100%|██████████| 5/5 [00:00<00:00,  8.63it/s]\n",
      "250417-162858: epoch=14, loss=0.433526, mean loss=0.466196: 100%|██████████| 5/5 [00:00<00:00,  8.54it/s]\n",
      "250417-162858: epoch=15, loss=0.429112, mean loss=0.463633: 100%|██████████| 5/5 [00:00<00:00,  8.59it/s]\n",
      "250417-162858: epoch=16, loss=0.432680, mean loss=0.462160: 100%|██████████| 5/5 [00:00<00:00,  8.50it/s]\n",
      "250417-162858: epoch=17, loss=0.409719, mean loss=0.458905: 100%|██████████| 5/5 [00:00<00:00,  8.62it/s]\n",
      "250417-162858: epoch=18, loss=0.371348, mean loss=0.456669: 100%|██████████| 5/5 [00:00<00:00,  8.58it/s]\n",
      "250417-162858: epoch=19, loss=0.440329, mean loss=0.454809: 100%|██████████| 5/5 [00:00<00:00,  8.48it/s]\n",
      "250417-162858: epoch=20, loss=0.398247, mean loss=0.452688: 100%|██████████| 5/5 [00:00<00:00,  8.38it/s]\n",
      "250417-162858: epoch=21, loss=0.382071, mean loss=0.450665: 100%|██████████| 5/5 [00:00<00:00,  8.37it/s]\n",
      "250417-162858: epoch=22, loss=0.419806, mean loss=0.449463: 100%|██████████| 5/5 [00:00<00:00,  8.37it/s]\n",
      "250417-162858: epoch=23, loss=0.427714, mean loss=0.448024: 100%|██████████| 5/5 [00:00<00:00,  8.39it/s]\n",
      "250417-162858: epoch=24, loss=0.432226, mean loss=0.446154: 100%|██████████| 5/5 [00:00<00:00,  8.38it/s]\n",
      "250417-162858: epoch=25, loss=0.442828, mean loss=0.445313: 100%|██████████| 5/5 [00:00<00:00,  8.41it/s]\n",
      "250417-162858: epoch=26, loss=0.381547, mean loss=0.443924: 100%|██████████| 5/5 [00:00<00:00,  8.37it/s]\n",
      "250417-162858: epoch=27, loss=0.407033, mean loss=0.443043: 100%|██████████| 5/5 [00:00<00:00,  8.49it/s]\n",
      "250417-162858: epoch=28, loss=0.449105, mean loss=0.442015: 100%|██████████| 5/5 [00:00<00:00,  8.40it/s]\n",
      "250417-162858: epoch=29, loss=0.430955, mean loss=0.441456: 100%|██████████| 5/5 [00:00<00:00,  8.29it/s]\n",
      "250417-162858: epoch=30, loss=0.397512, mean loss=0.440500: 100%|██████████| 5/5 [00:00<00:00,  7.86it/s]\n",
      "250417-162858: epoch=31, loss=0.379801, mean loss=0.438548: 100%|██████████| 5/5 [00:00<00:00,  8.27it/s]\n",
      "250417-162858: epoch=32, loss=0.393144, mean loss=0.437548: 100%|██████████| 5/5 [00:00<00:00,  8.24it/s]\n",
      "250417-162858: epoch=33, loss=0.387379, mean loss=0.436656: 100%|██████████| 5/5 [00:00<00:00,  8.43it/s]\n",
      "250417-162858: epoch=34, loss=0.476903, mean loss=0.435884: 100%|██████████| 5/5 [00:00<00:00,  8.44it/s]\n",
      "250417-162858: epoch=35, loss=0.394957, mean loss=0.434682: 100%|██████████| 5/5 [00:00<00:00,  8.32it/s]\n",
      "250417-162858: epoch=36, loss=0.431861, mean loss=0.433872: 100%|██████████| 5/5 [00:00<00:00,  8.25it/s]\n",
      "250417-162858: epoch=37, loss=0.378805, mean loss=0.432956: 100%|██████████| 5/5 [00:00<00:00,  8.36it/s]\n",
      "250417-162858: epoch=38, loss=0.416280, mean loss=0.432281: 100%|██████████| 5/5 [00:00<00:00,  8.37it/s]\n",
      "250417-162858: epoch=39, loss=0.390269, mean loss=0.431561: 100%|██████████| 5/5 [00:00<00:00,  8.36it/s]\n",
      "250417-162858: epoch=40, loss=0.417733, mean loss=0.430821: 100%|██████████| 5/5 [00:00<00:00,  8.32it/s]\n",
      "250417-162858: epoch=41, loss=0.415171, mean loss=0.429905: 100%|██████████| 5/5 [00:00<00:00,  7.82it/s]\n",
      "250417-162858: epoch=42, loss=0.382103, mean loss=0.428888: 100%|██████████| 5/5 [00:00<00:00,  8.28it/s]\n",
      "250417-162858: epoch=43, loss=0.414425, mean loss=0.428254: 100%|██████████| 5/5 [00:00<00:00,  8.32it/s]\n",
      "250417-162858: epoch=44, loss=0.376434, mean loss=0.427398: 100%|██████████| 5/5 [00:00<00:00,  8.27it/s]\n",
      "250417-162858: epoch=45, loss=0.389239, mean loss=0.426557: 100%|██████████| 5/5 [00:00<00:00,  8.33it/s]\n",
      "250417-162858: epoch=46, loss=0.380721, mean loss=0.425896: 100%|██████████| 5/5 [00:00<00:00,  8.16it/s]\n",
      "250417-162858: epoch=47, loss=0.399167, mean loss=0.425192: 100%|██████████| 5/5 [00:00<00:00,  8.32it/s]\n",
      "250417-162858: epoch=48, loss=0.407289, mean loss=0.424804: 100%|██████████| 5/5 [00:00<00:00,  8.26it/s]\n",
      "250417-162858: epoch=49, loss=0.364001, mean loss=0.424061: 100%|██████████| 5/5 [00:00<00:00,  8.33it/s]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-7:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-9:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-4:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-6:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-11:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-8:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-5:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "Exception in thread Thread-10:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1379, in _do_call\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return fn(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1362, in _run_fn\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1455, in _call_tf_sessionrun\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 980, in _bootstrap_inner\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    self.run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 766, in run_closure\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/threading.py\", line 917, in run\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 379, in thread_main\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    sess.run(self.enqueue, feed_dict={self.sample_placeholder: noisy_signal, self.target_placeholder: mask})\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 969, in run\n",
      "    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    result = self._run(None, fetches, feed_dict, options_ptr,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1192, in _run\n",
      "    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    results = self._do_run(handle, final_targets, final_fetches,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1372, in _do_run\n",
      "    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError    return self._do_call(_run_fn, feeds, fetches, targets, options,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/client/session.py\", line 1398, in _do_call\n",
      "    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      ": : Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      ": Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      ": Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      "Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      ": Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      ": Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n",
      ": Graph execution error:\n",
      "\n",
      "Detected at node 'create_inputs/padding_fifo_queue_enqueue' defined at (most recent call last):\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "      return _run_code(code, main_globals, None,\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "      app.launch_new_instance()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "      app.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "      self.io_loop.start()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "      self.asyncio_loop.run_forever()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "      self._run_once()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "      handle._run()\n",
      "    File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "      self._context.run(self._callback, *self._args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "      await self.process_one()\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "      await dispatch(*args)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "      await result\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "      await super().execute_request(stream, ident, parent)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "      reply_content = await reply_content\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "      res = shell.run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "      return super().run_cell(*args, **kwargs)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "      result = self._run_cell(\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "      result = runner(coro)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "      coro.send(None)\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "      if await self.run_code(code, result, async_=asy):\n",
      "    File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "      exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "    File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "      model, sess = main(args)\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "      data_reader = DataReader(\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "      self.add_queue()\n",
      "    File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "      self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "Node: 'create_inputs/padding_fifo_queue_enqueue'\n",
      "Enqueue operation was cancelled\n",
      "\t [[{{node create_inputs/padding_fifo_queue_enqueue}}]]\n",
      "\n",
      "Original stack trace for 'create_inputs/padding_fifo_queue_enqueue':\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/Users/tocochan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/yy/h4ndzppd11l1g6sl_d1_jymw0000gq/T/ipykernel_47422/3521231946.py\", line 30, in <module>\n",
      "    model, sess = main(args)\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/train.py\", line 506, in main\n",
      "    data_reader = DataReader(\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 201, in __init__\n",
      "    self.add_queue()\n",
      "  File \"/Users/tocochan/self_study/2025_geosci/earthquake/notebook/../model/DeepDenoiser/deepdenoiser/data_reader.py\", line 214, in add_queue\n",
      "    self.enqueue = self.queue.enqueue([self.sample_placeholder, self.target_placeholder])\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py\", line 347, in enqueue\n",
      "    return gen_data_flow_ops.queue_enqueue_v2(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py\", line 4069, in queue_enqueue_v2\n",
      "    _, _, _op, _outputs = _op_def_library._apply_op_helper(\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py\", line 795, in _apply_op_helper\n",
      "    op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n",
      "  File \"/Users/tocochan/.pyenv/versions/myenv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 3381, in _create_op_internal\n",
      "    ret = Operation.from_node_def(\n",
      "\n"
     ]
    }
   ],
   "source": [
    "args = argparse.Namespace(\n",
    "    mode=\"train\",\n",
    "    train_signal_dir=\"../model/DeepDenoiser/Dataset/train\",\n",
    "    train_signal_list=\"../model/DeepDenoiser/Dataset/train.csv\",\n",
    "    train_noise_dir=\"../model/DeepDenoiser/Dataset/train\",\n",
    "    train_noise_list=\"../model/DeepDenoiser/Dataset/train.csv\",\n",
    "    model_dir=\"../model/DeepDenoiser/log/250417-092544\",\n",
    "    valid_signal_list=None,\n",
    "    valid_noise_list=None,\n",
    "    log_dir=\"./log\",\n",
    "    depth=6,\n",
    "    filters_root=8,\n",
    "    kernel_size=[3, 3],\n",
    "    pool_size=[2, 2],\n",
    "    dilation_rate=[1, 1],\n",
    "    class_weights=[1.0, 1.0],\n",
    "    loss_type=\"cross_entropy\",\n",
    "    weight_decay=0,\n",
    "    optimizer=\"adam\",\n",
    "    learning_rate=0.001,\n",
    "    decay_step=5,\n",
    "    decay_rate=0.9,\n",
    "    momentum=0.9,\n",
    "    batch_size=20,\n",
    "    summary=True,\n",
    "    drop_rate=0,\n",
    "    epochs=50,\n",
    ")\n",
    "\n",
    "model, sess = main(args)\n",
    "deepdenoiser = WrappedModel(model, sess, denoiser_name=\"DeepDenoiser\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ③デノイジングと評価"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0/4935\n",
      "100/4935\n",
      "200/4935\n",
      "300/4935\n",
      "400/4935\n",
      "500/4935\n",
      "600/4935\n",
      "700/4935\n",
      "800/4935\n",
      "900/4935\n",
      "1000/4935\n",
      "1100/4935\n",
      "1200/4935\n",
      "1300/4935\n",
      "1400/4935\n",
      "1500/4935\n",
      "1600/4935\n",
      "1700/4935\n",
      "1800/4935\n",
      "1900/4935\n",
      "2000/4935\n",
      "2100/4935\n",
      "2200/4935\n",
      "2300/4935\n",
      "2400/4935\n",
      "2500/4935\n",
      "2600/4935\n",
      "2700/4935\n",
      "2800/4935\n",
      "2900/4935\n",
      "3000/4935\n",
      "3100/4935\n",
      "3200/4935\n",
      "3300/4935\n",
      "3400/4935\n",
      "3500/4935\n",
      "3600/4935\n",
      "3700/4935\n",
      "3800/4935\n",
      "3900/4935\n",
      "4000/4935\n",
      "4100/4935\n",
      "4200/4935\n",
      "4300/4935\n",
      "4400/4935\n",
      "4500/4935\n",
      "4600/4935\n",
      "4700/4935\n",
      "4800/4935\n",
      "4900/4935\n",
      "Total Loss = 10.718760659385383\n"
     ]
    }
   ],
   "source": [
    "experiment(deepdenoiser, \"DeepDenoiser\")"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
